### ISSUE TITLE
Can't chose install location

### ISSUE THREAD

**Issue by DigitalNikki** [satisfactorymodding/SatisfactoryModManager#60]
You can try to chose where you want this installed to, but you can't chose. It will always install to Satisfactory Mod Manager regardless if that's where you want it or not. Users should not be required to alter the program for this to work correctly, if they want it installed to X:/SatisfactoryModLancher then that it where it should be installed to. No extra folders, no Satisfactory Mod Manager.

**Comment by SirChopwood** [comment]
Can i ask why you would need to move it? It installs itself in a safe location that is acceptable for applications of its nature and ensures it works on all machines without any form of user error possible.

**Comment by DigitalNikki** [comment]
Because it doesn't work anymore, and I can't do anything about it in the crappy %appdata% location.

**Comment by mircearoata** [comment]
What do you mean by it doesn't work anymore?

You can uninstall it and choose the install dir now (actually for quite some months now) but it will still create the folder Satisfactory Mod Manager in which it installs its files, because otherwise people could choose C:\ as the install dir and overwrite Windows with SMM files

**Comment by DigitalNikki** [comment]
I finally got it working. For some reason it didn't remove the registry keys when I uninstalled it. I tried removing them manually, but I had to restore the backup and manually edit them to make it work.

It would get stuck trying to update or install, and not go past that.

**Comment by mircearoata** [comment]
That has been fixed ages ago, when "uninstalled" by deleting the folder it left the registry keys behind, but now the installer removes the registry keys just in case they are still there

**Comment by DigitalNikki** [comment]
The install location still can't be chosen, and it still has the same issue with breaking with each update.

**Comment by DigitalNikki** [comment]
It's possible, but to test that I would need to know all possible locations in the registry to clean up. For me if I chose D:\SomeRandomLocation it forcefully installs to D:\SomeRandomLocation\Satisfactory Mod Manager, and to me that removes my choice of where to install it. If I tell it to install to D:\SomeRandomLocation I expect Satisfactory Mod Manager.exe to be at D:\SomeRandomLocation\Satisfactory Mod Manager.exe not D:\SomeRandomLocation\Satisfactory Mod Manager\Satisfactory Mod Manager.exe

I also can't set the location of the game, and yes I own it on Steam. I maintain two installations at the same time, experimental and stable. I can't chose the location for, or that experimental is installed. Experimental is installed with SteamCMD after logging into my account. I'm unaware of another option to install a game twice.

From a batch file, there is more to it than this but this is the command that installs and updates it.
SteamCmd.exe ^
+force_install_dir "R:\Games\SatisfactoryExperimental" ^
+login somesteamaccount ^
+app_update 526870 validate -beta experimental ^
+quit

**Comment by mircearoata** [comment]
The app name dir is [appended by electron-builder](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/assistedInstaller.nsh#L33-L40) when the chosen directory already exists and I can not change that. And it does it for a good reason, like I said before, so that it will never overwrite other files or folders that are already there.

However, it only appends it when the folder already exists, so if `D:\SomeRandomLocation` does not exist, it will create that folder and install the files in there, without another directory.

The registry key is either `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\05aa181a-e2c4-5231-ae02-02af49144086` or `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\05aa181a-e2c4-5231-ae02-02af49144086`, most likely the first one if you installed it per-user.

As for SteamCMD, it doesn't support it yet, because it doesn't store its info in the same location as the Steam app, but I could make it look for SteamCMD in the `PATH` to find the steamapps dir.
